# docker-compose.yaml
# docker-compose up -d
# docker-compose stop
# docker-compose start
# docker-compose ps
version: '3'
services:
  backend:
    image: vdigital/skynet:v1
    volumes:
      - ./php:/var/www/html
    ports:
      - 8083:80
  frontend:
    image: nginx:1.13.3-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    environment:
      - AUTHOR=vdigi
    ports:
      # HTTP PORT
      - 8082:80
